server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # This try_files directive is the key to making React Router work correctly.
  location / {
    try_files $uri /index.html;
  }
}
